### ISSUE TITLE
Add initial project files and structure

### ISSUE THREAD

**Issue by lhp1507** [lhp1507/car-comparison-2025#6]
## Files to be added:

1. Basic HTML structure
```html
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>So sánh Sedan hạng B 2025</title>
    <link href="css/styles.css" rel="stylesheet">
    <script src="js/main.js" defer></script>
</head>
<body>
    <!-- Content will be added in next commit -->
</body>
</html>
```

2. Initial CSS setup
```css
/* Base styles */
:root {
    --primary-color: #2c3e50;
    --secondary-color: #34495e;
    --accent-color: #3498db;
}

* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
}

body {
    font-family: 'Montserrat', sans-serif;
    line-height: 1.6;
}
```

3. Basic JavaScript structure
```javascript
document.addEventListener('DOMContentLoaded', () => {
    // Initialize app
    console.log('App initialized');
});
```

## Tasks:
- [ ] Create directory structure
- [ ] Add basic HTML file
- [ ] Add initial CSS
- [ ] Add JavaScript skeleton
- [ ] Setup Git hooks
- [ ] Add EditorConfig
- [ ] Add VS Code settings

## Note:
This is just the initial structure. Content and features will be added in subsequent commits.
