### ISSUE TITLE
Feature: Add core functionality and GitHub Pages setup

### ISSUE THREAD

**Issue by lhp1507** [lhp1507/car-comparison-2025#7]
### 1. Add Filter and Comparison Features
```javascript
// Add to main.js
const carFeatures = {
  comparison: {
    dimensions: ['Dài x Rộng x Cao', 'Chiều dài cơ sở', 'Khoảng sáng gầm'],
    engine: ['Động cơ', 'Công suất tối đa', 'Mô-men xoắn cực đại'],
    features: ['Số túi khí', 'Hệ thống phanh', 'Camera lùi'],
    price: ['Giá niêm yết', 'Chi phí lăn bánh', 'Chi phí bảo dưỡng']
  }
};

function createComparisonTable() {
  // Implementation
}

function initializeFilters() {
  // Enhanced implementation
}
```

### 2. Add GitHub Pages Configuration
- Create `.github/workflows/pages.yml`
```yaml
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
```

### 3. Enhanced Styling
```css
/* Add to styles.css */
.comparison-table {
  width: 100%;
  border-collapse: collapse;
  margin: 2rem 0;
}

.comparison-table th,
.comparison-table td {
  padding: 1rem;
  border: 1px solid var(--border-color);
  text-align: left;
}

.comparison-table th {
  background: var(--light-gray);
  font-weight: 600;
}

.filters {
  display: flex;
  gap: 1rem;
  margin: 2rem 0;
  flex-wrap: wrap;
}

.filter-btn {
  padding: 0.5rem 1rem;
  border: none;
  background: var(--light-gray);
  border-radius: var(--border-radius);
  cursor: pointer;
  transition: all 0.3s;
}

.filter-btn.active {
  background: var(--accent-color);
  color: white;
}
```

### 4. Reviews Section
```html
<!-- Add to index.html -->
<section id="reviews" class="reviews container">
  <h2>Đánh giá từ người dùng</h2>
  <div class="reviews-grid">
    <!-- Reviews will be populated by JavaScript -->
  </div>
</section>
```

## Tasks
- [ ] Implement comparison table functionality
- [ ] Add filter system
- [ ] Setup GitHub Pages deployment
- [ ] Add reviews section
- [ ] Add responsive design improvements
- [ ] Add car data
- [ ] Test deployment

## Testing
- Test all features on desktop and mobile
- Verify GitHub Pages deployment
- Check responsive design breakpoints

## Notes
After merging this PR:
1. GitHub Pages will be automatically deployed
2. Site will be available at https://lhp1507.github.io/car-comparison-2025
